import { and, eq, sql } from "drizzle-orm";

import { type ActionOutcome, runAction } from "#lib/server/actions.ts";
import type { Db, Transaction } from "#lib/server/db/client.ts";
import { seenMovies, users } from "#lib/server/db/schema.ts";

// The only module that changes seen lists. Each change is an action (applied
// at most once per action ID, see actions.ts) and bumps the user's
// `seen_version` in the same transaction, so every watch session the user is
// in can notice the change.

export interface SeenListChange {
  /** Generated by the browser, so a retried request carries the same ID. */
  actionId: string;
  userId: string;
  movieId: number;
}

/** Adds a movie to the user's seen list. Already on it: nothing changes. */
export function addToSeenList(
  db: Db,
  { actionId, userId, movieId }: SeenListChange
): Promise<ActionOutcome> {
  const action = {
    id: actionId,
    userId,
    type: "seen_list_add",
    movieId,
  } as const;
  return runAction(db, action, async (tx) => {
    const added = await tx
      .insert(seenMovies)
      .values({ userId, movieId })
      .onConflictDoNothing()
      .returning({ movieId: seenMovies.movieId });
    if (added.length > 0) await bumpSeenVersion(tx, userId);
  });
}

/** Removes a movie from the user's seen list. Not on it: nothing changes. */
export function removeFromSeenList(
  db: Db,
  { actionId, userId, movieId }: SeenListChange
): Promise<ActionOutcome> {
  const action = {
    id: actionId,
    userId,
    type: "seen_list_remove",
    movieId,
  } as const;
  return runAction(db, action, async (tx) => {
    const removed = await tx
      .delete(seenMovies)
      .where(
        and(eq(seenMovies.userId, userId), eq(seenMovies.movieId, movieId))
      )
      .returning({ movieId: seenMovies.movieId });
    if (removed.length > 0) await bumpSeenVersion(tx, userId);
  });
}

// Only called when the list really changed: a no-op shouldn't make watch
// sessions refresh.
async function bumpSeenVersion(tx: Transaction, userId: string): Promise<void> {
  await tx
    .update(users)
    .set({ seenVersion: sql`${users.seenVersion} + 1` })
    .where(eq(users.id, userId));
}
